StaffSoftwareQuery/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StaffSoftwareQuery.Models;

namespace StaffSoftwareQuery.Controllers
{
    public class StaffController : Controller
    {
        //
        // GET: /Staff/
        StaffEntities db;

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetSoftwareData() {
            using (db = new StaffEntities())
            {
                var es = db.ReadFile
                    .Select(g=>new { 
                        dt=g.ImportDate,
                        rd=g.ReadLine,
                        usr=g.UserName
                    })
                    .OrderBy(x => x.usr)
                    .ToList();
                var jes=Json(new { members = es });
                jes.MaxJsonLength = int.MaxValue;
                return jes;
            }
        }

        [HttpPost]
        public JsonResult Write2DB()
        {
            using (db = new StaffEntities())
            {
                try
                {
                    db.ImportFiles(@"E:\FileToDB\", @"E:\FileToDB\Archive\", "*.txt", "MergeBCPData2");
                    return Json("OK");
                }
                catch (Exception ex) {
                    return Json(ex.ToString());
                }
            }
        }

        public ActionResult About() {
            return View();
        }

    }
}

StaffSoftwareQuery/Views/Shared/_Layout.cshtml

<html lang="zh">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - ONElab IS app.</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css") @Scripts.Render("~/bundles/modernizr")
        <link href='~/bower_components/semantic-ui/dist/semantic.min.css' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left"><p class="site-title">@Html.ActionLink("ONElab Staff Sofeware Infor.", "Index", "Staff")</p></div>
                <div class="float-right">
                    <section id="login"><span class="username">@User.Identity.Name</span>!</section>
                    <nav>
                        <ul id="menu"><li>@Html.ActionLink("操作注意事項", "About", "Staff")</li></ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - ONElab IS Application. ver:3a03ef</p>
                </div>
            </div>
        </footer>
        <script type="text/javascript" src="~/Scripts/dist/entry-dev.js"></script>
        @RenderSection("JS", required: false)
    </body>
</html>